site_name: Python base
site_description: курс по основам языка Python для вузов


docs_dir: docs/markdowns
theme:
  custom_dir: overrides
  name: material
  icon:
    logo: material/language-python
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  hide:
    - navigation
    - toc
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: light blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: light blue

nav:
  - Информация о курсе: index.md
  - Раздел 1. Основы языка Python:
    - Что такое Python? Начало работы: part_1/intro.md
    - Типы данных. Целые числа и числа с плавающей точкой: part_1/int_and_float.md
    - Переменные. Строки: part_1/vars_and_str.md
    - Задача №1. Вывод песен из строки: part_1/first_task.md
    - Коллекции. Списки и кортежи: part_1/list_and_tuples.md
    - Задача №2. Изменение списка покупок. Форматированный вывод: part_1/second_task.md
    - Условный оператор if. Операторы цикла while и for: part_1/if_while_for.md
    - Задача №3. Словари и их свойства. Списковое включение: part_1/third_task.md
    - Функции. Свойства и параметры функций: part_1/functions.md
  - Раздел 2. Импорт. Работа с файлами:
    - Импорт. Работа с файлами: part_2/intro.md
    - Импорт из модулей и пакетов: part_2/module_and_package.md
    - Стандартная библиотека Python. Модули pprint, sys, decimal: part_2/decimal_task.md
    - Обработка случайных значений. Модуль random: part_2/random_task.md
    - Обработка форматов даты и времени. Модули time, datetime: part_2/datetime_task.md
    - Внешние пакеты. Пакеты pandas, python-docx: part_2/site_package.md
    - Режимы открытия файлов. Работа с форматами csv, json, xml, yaml: part_2/open_csv_json.md
    - Дополнительные темы:
      - Кодировки и байты: part_2/bytes.md
      - Регулярные выражения: part_2/regexp.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pyshkovni
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCFl8u5LGFv0UqhfP5whEoVA
    - icon: fontawesome/brands/telegram
      link: https://t.me/pyshkovni
    - icon: fontawesome/brands/vk
      link: https://vk.com/pyshkovni

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2024 <a href="https://github.com/pyshkovni"  target="_blank" rel="noopener">Nikita Pyshkov</a>
